name: Mimic Build Process Init

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: build
      run: |
        git checkout release/next 2>/dev/null || git checkout -b release/next
        rm -rf build
        mkdir -p ./build && cp *.txt ./build/
        git config user.name "${{ github.actor }}-bot" && git config user.email "${{ github.actor }}@users.noreply.gihub.com"
        if ! git diff-index --quiet HEAD --; then
          git add .
          git commit -m "Commit:Build Output"
          git push origin release/next
        fi
        
        if [ ! -f ./RELEASE_LOCK ]; then
          echo '::set-output name=MAKE_PR::1'
        fi
        
    - name: Create Pull Request
      if: steps.build.outputs.MAKE_PR == '1'
      id: create_pull
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        commit-message: Update report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        base: master
        branch: release/next
        delete-branch: true
        title: 'Next Release'
        body: |
          Next Release PR
          - Updated with *today's* date
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        milestone: 1
        draft: false
  
    - name: View CPR output
      run: echo ${{ steps.cpr.outputs }}
  
    - name: Check outputs & Create RELEASE_LOCK
      id: release_lock
      if: steps.build.outputs.MAKE_PR == '1'
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
        
        echo ${{ steps.cpr.outputs.pull-request-number }} > ./.RELEASE_LOCK
        
        git checkout release/next 2>/dev/null || git checkout -b release/next
        git config user.name "${{ github.actor }}-bot" && git config user.email "${{ github.actor }}@users.noreply.gihub.com"
        if ! git diff-index --quiet HEAD --; then
          git add .
          git commit -m "Commit:Release Lock File"
          git push origin release/next
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
