name: Mimic Build Process Init

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: build
      run: |
        git checkout release/next 2>/dev/null || git checkout -b release/next
        git branch
        rm -rf build
        mkdir -p ./build && cp *.txt ./build/
        git config user.name "${{ github.actor }}-bot" && git config user.email "${{ github.actor }}@users.noreply.gihub.com"
        if ! git diff-index --quiet HEAD --; then
          git add .
          git commit -m "Commit:Build Output"
          git push origin release/next
        fi
        
        if [ ! -f ./RELEASE_LOCK ]; then
          echo '::set-output name=MAKE_PR::1'
        fi
        
    - name: Create Pull Request
      if: steps.build.outputs.MAKE_PR == '1'
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "release/next"
        pr_title: "Next Release"
        pr_body: ":crown: *An automated PR*"
        # pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
        pr_label: "auto-pr"                               # Comma-separated list (no spaces)
        pr_milestone: "Milestone 1"                       # Milestone name
        pr_draft: false                                    # Creates pull request as draft
        # pr_allow_empty: true                              # Creates pull request even if there are no changes
        github_token: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Check outputs & Create RELEASE_LOCK
      id: release_lock
      if: steps.build.outputs.MAKE_PR == '1'
      run: |
        # echo "Pull Request Number - ${{ steps.create_pull.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.create_pull.outputs.pr_url }}"
        
        echo ${{ steps.create_pull.outputs.pr_url }} > ./.RELEASE_LOCK
        
        git checkout release/next 2>/dev/null || git checkout -b release/next
        git config user.name "${{ github.actor }}-bot" && git config user.email "${{ github.actor }}@users.noreply.gihub.com"
        if ! git diff-index --quiet HEAD --; then
          git add .
          git commit -m "Commit:Release Lock File"
          git push origin release/next
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
