name: Mimic Build Process Init

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - run: git checkout release/next 2>/dev/null || git checkout -b release/next
    - run: rm -rf build
    - run: mkdir -p ./build && cp *.txt ./build/
    - run: echo ${{ github.actor }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
